name: Fineract backend build
on:
  push:
    branches:
      - develop

jobs:
  login:
    runs-on: ubuntu-22.04
    steps:
    -
      name: Login to Jfrog Artifactory
      uses: docker/login-action@v2
      with:
        registry: sendy-docker-local.jfrog.io
        username: ${{ secrets.JFROG_USERNAME }}
        password: ${{ secrets.JFROG_ACCESS_TOKEN }}

    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1

    - name: Build fineract docker image
      run: ./gradlew :fineract-provider:jibDockerBuild -x test --info
    
    - name: Upload docker image to Jfrog
      run: |
        TAG=$(date +%Y-%m-%d-%H-%M)
        docker tag fineract:latest sendy-docker-local.jfrog.io/fineract:prod_$TAG
        docker push sendy-docker-local.jfrog.io/fineract:prod_$TAG
  